### ISSUE TITLE
rate limit is not working correctly

### ISSUE THREAD

**Issue by parro-it** [nodemailer/nodemailer-smtp-pool#8]
Mail are delivered at a high rate, even if I specify a rate limit of 1 message per sec.
I digged a bit within source code, if I understood correctly, all waiting mail are sent once the timeout of 1s expire, even if they are more than the rateLimit specified.

**Comment by andris9** [comment]
Try to set `maxConnections` to 1 if you want to send only a single message in a second

**Comment by parro-it** [comment]
Already tryed, but without success. Looking sources, I think the problem is that mails are correctly put in a wait queue when rate limit is reached. But once timeout occur, all mails in queue are sent at once, even if the number of mails oversize the rate

**Comment by dtoubelis** [comment]
Same here. I send emails to `mailtrap.io` during unit tests. My `mailtrap` account has limit of 2 messages per second, so I set `pool=true`, `rateLimit=1`, `maxConnections=1` and I send 5 messages at a time during the test. However, I always get this error:
```
Error: Data command failed: 550 5.7.0 Requested action not taken: too many emails per second
```
However, if i also set `maxMessages=1` it works but it feels wrong.
